spring:
  application:
    name: mybatis-plus-springboot
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/mybatis-plus-demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456

logging:
  level:
    org:
      lhyf: debug


mybatis-plus:
  # 指定Mybatis 原生配置文件位置
  #  config-location: classpath:mybatis-config.xml

  # classpath* 带*号,可以扫描所有依赖包下的路径
  mapper-locations:
  - classpath*:mapper/*.xml

  # 配置别名包
  type-aliases-package: org.lhyf.mp.boot.entity
  global-config:
    db-config:
      # 全局的ID生成策略, 设置后, 可以省略实体对象中的 @TableId(type = IdType.AUTO)配置
      id-type: auto
      # 全局的表名的前缀,配置后可以省略@TableName()配置
#      table-prefix: t_

  # 开启驼峰命名(Mybatis-plus 默认开启)
  configuration:
    map-underscore-to-camel-case: true
    # 禁用缓存(默认true)
    cache-enabled: true

